// src/data/booksData.ts
const books = [
    {
      id: 0,
      title: "Don't Make Me Think",
      author: "Steve Krug",
      price: 1500,
      discountPrice: 2000,
      image: require("../assests1/Books.png"),
      rating: 4.5,
      stock: true,
    },
    {
      id: 1,
      title: "Artificial Intelligence",
      author: "Sam Altman",
      price: 1200,
      discountPrice: 1800,
      image: require("../assests1/Books.png"),
      rating: 4.2,
      stock: true,
    },
    {
      id: 2,
      title: "UX Design",
      author: "Jane Smith",
      price: 1300,
      discountPrice: 1900,
      image: require("../assests1/Books.png"),
      rating: 4.7,
      stock: false, // Example out of stock book
    },
    // Add more books to reach at least 12 for pagination (e.g., duplicate or create new ones)
    {
      id: 3,
      title: "Web Development Basics",
      author: "Alice Johnson",
      price: 1100,
      discountPrice: 1500,
      image: require("../assests1/Books.png"),
      rating: 4.3,
      stock: true,
    },
    {
      id: 4,
      title: "JavaScript Essentials",
      author: "Bob Brown",
      price: 1250,
      discountPrice: 1700,
      image: require("../assests1/Books.png"),
      rating: 4.6,
      stock: false,
    },
    // Add 7 more books to reach 12 for the first page
    {
      id: 5,
      title: "Python for Beginners",
      author: "Carol White",
      price: 1300,
      discountPrice: 1800,
      image: require("../assests1/Books.png"),
      rating: 4.4,
      stock: true,
    },
    {
      id: 6,
      title: "CSS Mastery",
      author: "David Lee",
      price: 1150,
      discountPrice: 1600,
      image: require("../assests1/Books.png"),
      rating: 4.5,
      stock: true,
    },
    {
      id: 7,
      title: "HTML Fundamentals",
      author: "Eve Davis",
      price: 1200,
      discountPrice: 1650,
      image: require("../assests1/Books.png"),
      rating: 4.2,
      stock: false,
    },
    {
      id: 8,
      title: "Node.js Guide",
      author: "Frank Miller",
      price: 1400,
      discountPrice: 1900,
      image: require("../assests1/Books.png"),
      rating: 4.7,
      stock: true,
    },
    {
      id: 9,
      title: "React Advanced",
      author: "Grace Taylor",
      price: 1350,
      discountPrice: 1850,
      image: require("../assests1/Books.png"),
      rating: 4.6,
      stock: true,
    },
    {
      id: 10,
      title: "Angular Basics",
      author: "Hank Wilson",
      price: 1100,
      discountPrice: 1500,
      image: require("../assests1/Books.png"),
      rating: 4.3,
      stock: false,
    },
    {
      id: 11,
      title: "Vue.js Essentials",
      author: "Ivy Clark",
      price: 1250,
      discountPrice: 1700,
      image: require("../assests1/Books.png"),
      rating: 4.5,
      stock: true,
    },
  ];
  
  export default books;